### ISSUE TITLE
No module named 'django.utils.six.moves.http_client'; django.utils.six.moves is not a package

### ISSUE THREAD

**Issue by aniketmaithani** [maxolasersquad/orthosie#12]
I have installed python3 and django 1.6 on my machine. My OS configurations are as follows : 10.10.1 MAC OS X Yosemite. 

I have done the above installation by creating a virtual environment. 

The installation proceeds smoothely but when I open 127.0.0.1/admin or any other related URL for that matter. I get the above mentioned error. 

How to fix this?

**Comment by maxolasersquad** [comment]
Use /register and /inventory. I do not use any of the admin generators.

**Comment by maxolasersquad** [comment]
On a side note, thanks for taking the time out to review this software and feel free to post any more issues for any problems you find or suggestions you have.

**Comment by maxolasersquad** [comment]
Can you confirm that going to /register and /inventory work for you?
