### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by kkoci** [maxolasersquad/orthosie#13]
Hi, I'm trying to run this app, I already have Python 3.3.1 installed on my machine. (Win 7)

Made a virtualenv, but no requirements file is in, could you please provide one?

Thanks in advance!

**Comment by maxolasersquad** [comment]
Sure will. I'll have this added in a few days.

**Comment by kkoci** [comment]
Thank you, I manage to run the app, I'm using Django 1.7 and rest_framework, that's it

**Comment by maxolasersquad** [comment]
Fixed in #14 .
