### ISSUE TITLE
TemplateDoesNotExist at /register

### ISSUE THREAD

**Issue by eracle** [maxolasersquad/orthosie#30]
Hi!
I'm trying to deploy the project using python 3.4.3, a separate virtualenv with the requirements suggested, I'm actually installed all the requirements in common.txt dev.txt and prod.txt.
I'm using on my local machine Ubuntu 14.04

With packages in this virtualenv:
Django (1.10.1)
djangorestframework (3.4.6)
pep8 (1.7.0)
pip (8.1.2)
pyflakes (1.3.0)
python-memcached (1.58)
setuptools (27.1.2)
six (1.10.0)
wheel (0.29.0)

After that I searched for the manage.py's syncdb command, but unfortunately I didn't find it, so I run makemigrations and then migrate commands as [this](http://stackoverflow.com/questions/29683494/what-should-i-use-instead-of-syncdb-in-django-1-9) post points out.

Now, when I run the server and I access to the register page I get this error:

`
Environment:

Request Method: GET
Request URL: http://localhost:8000/register/

Django Version: 1.10.1
Python Version: 3.4.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'register',
 'inventory')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')

Template loader postmortem
Django tried loading these templates, in this order:

Using engine :
    This engine did not provide a list of tried templates.

Traceback:

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/eracle/python/projects/orthosie/register/views.py" in index
  14.     return render(request, 'register/index.html', context)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/template/loader.py" in render_to_string
  67.         template = get_template(template_name, using=using)

File "/home/eracle/python/virtualenvs/orthosie/lib/python3.4/site-packages/django/template/loader.py" in get_template
  25.     raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /register/
Exception Value: register/index.html
`

I think is related with how this django version search for the template dir.
I'm quite new with django, so after some experience I can try to afford the problem in a better way.

**Comment by maxolasersquad** [comment]
I think you are probably right about the Djanogo version. Can you try with Django 1.8, not 1.9 and see if that clears it up? I'll take a look this evening to see what I come up with.

**Comment by maxolasersquad** [comment]
It might also help to check out tagged version 1.2. That should clear up any issues.

**Comment by eracle** [comment]
Yes, the problem was on how the new Django version search for the templates file.
I partially fixed it. 
As a perfect side project while I'm learning mastering Django, I created a [branch](https://github.com/eracle/orthosie/tree/django1.10) of your project in order to let it work properly with django1.10.
After I will fix all the problems I will make a pull request.
Best Regards

**Comment by eracle** [comment]
Easier than I thought, pull request [here](https://github.com/maxolasersquad/orthosie/pull/31).

**Comment by maxolasersquad** [comment]
Fixed by #31
